version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies using node 18"
      - npm ci 
      - echo "Done installing dependencies ====>"
  build:
    commands:
      - echo "Building the React Project"
      - npm run build
      - echo "Done building the project ==> Exporting artifcats"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist